SELECT CURRENT_REGION();
SELECT SYSTEM$ALLOWLIST_PRIVATELINK();
SELECT CURRENT_ACCOUNT();

-- Create/Replace Storage Integration
DESC INTEGRATION s3_int_weather_sgp;
CREATE OR REPLACE STORAGE INTEGRATION s3_int_weather_sgp
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::021740144457:role/SnowflakeS3AceessRole01'
  STORAGE_ALLOWED_LOCATIONS = ('s3://weather-raw-json-namitha-01/');

-- Get External ID for IAM role configuration (if needed again)
DESC INTEGRATION s3_int_weather_sgp;

SHOW INTEGRATIONS;
SHOW INTEGRATIONS LIKE 'S3_INT_WEATHER_SGP';

SELECT CURRENT_ROLE();
SELECT SYSTEM$GET_SNOWFLAKE_PLATFORM_INFO();